Repository ton-studio/ton-labels, pull requests merged in 2025-03, with the labels that each got.

#101 Add labels Yescoin
  assets/gaming/yescoin.json
Labels: ready-for-merge

#107 add scammer
  assets/scammer/scammer.json
Labels: botnets/scammers

#128 Add labels Farm1 Paws receiver
  assets/scripted-activity/sybil_EQBwh0WS.json
Labels: botnets/scammers

#129 Add labels Farm2 Paws sender
  assets/scripted-activity/sybil_EQDByRqo.json
Labels: botnets/scammers

#130 Add labels Farm3 Paws sender
  assets/scripted-activity/farm3_paws.json
Labels: botnets/scammers

#132 Add labels Farm4 Duck
  assets/scripted-activity/sybil_EQC3UkfA.json
Labels: botnets/scammers

#108 Label possible botner owner
  assets/scripted-activity/sybil_EQBPnnUx.json
Labels: botnets/scammers

#177 Add label OKX wallets
  assets/cex/okx.json
Labels: WIP
